export let Genres: { question: string; id: number; choices: ({ val: string; text: string } | { val: string; text: string } | { val: string; text: string } | { val: string; text: string } | { val: string; text: string })[] };
Genres = {
    question:
        "Please select 0 to 3 genres",
    id: 3,
    choices: [
        {text: "afrobeat", val: "afrobeat",},
        {text: "alt-rock", val: "alt-rock",},
        {text: "alternative", val: "alternative",},
        {text: "blues", val: "blues",},
        {text: "brazil", val: "brazil",},
        {text: "british", val: "british", },
        {text: "chill", val: "chill", },
        {text: "classical", val: "classical", },
        {text: "club", val: "club", },
        {text: "country", val: "country", },
        {text: "dance", val: "dance", },
        {text: "disco", val: "disco", },
        {text: "dubstep", val: "dubstep", },
        {text: "edm", val: "edm", },
        {text: "emo", val: "emo", },
        {text: "folk", val: "folk", },
        {text: "french", val: "french", },
        {text: "funk", val: "funk", },
        {text: "garage", val: "garage", },
        {text: "german", val: "german", },
        {text: "grunge", val: "grunge", },
        {text: "hardcore", val: "hardcore", },
        {text: "hip-hop", val: "hip-hop", },
        {text: "indian", val: "indian", },
        {text: "indie", val: "indie", },
        {text: "indie-pop", val: "indie-pop", },
        {text: "industrial", val: "industrial", },
        {text: "j-pop", val: "j-pop", },
        {text: "jazz", val: "jazz", },
        {text: "k-pop", val: "k-pop", },
        {text: "latino", val: "latino", },
        {text: "malay", val: "malay", },
        {text: "mandopop", val: "mandopop", },
        {text: "metal", val: "metal", },
        {text: "new-age", val: "new-age", },
        {text: "new-release", val: "new-release", },
        {text: "opera", val: "opera", },
        {text: "party", val: "party", },
        {text: "philippines-opm", val: "philippines-opm", },
        {text: "pop", val: "pop", },
        {text: "punk", val: "punk", },
        {text: "punk-rock", val: "punk-rock", },
        {text: "r-n-b", val: "r-n-b", },
        {text: "rainy-day", val: "rainy-day", },
        {text: "reggae", val: "reggae", },
        {text: "rock", val: "rock", },
        {text: "sad", val: "sad", },
        {text: "samba", val: "samba", },
        {text: "sertanejo", val: "sertanejo", },
        {text: "sleep", val: "sleep", },
        {text: "soul", val: "soul", },
        {text: "spanish", val: "spanish", },
        {text: "synth-pop", val: "synth-pop", },
        {text: "techno", val: "techno", },
        {text: "work-out", val: "work-out", },
        {text: "world-music", val: "world-music", },
    ]
};
