name: Self-hosted Java CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Backend tests with Maven
        run: mvn -f back/pom.xml test
      - uses: actions/setup-node@v3
        with:
          node-version: '19.7.0'
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'
      - run: npm install
        working-directory: frontend
      - run: npm test
        working-directory: frontend